Data Preprocessing Tools

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing Dataset

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [3]:
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [4]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


Missing Data handelling

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x.iloc[:, 1:3])
x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3])

In [9]:
print(x)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000


Encoding categorical Data

Encoding independent variables

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

Encoding the dependent variable

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting dataset into train and test

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Feature scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [22]:
print(x_test)

[[ 0.77459667 -0.77459667  1.73205081 -0.77459667 -1.46618179 -0.9069571 ]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.44973664  0.20564034]]


In [23]:
print(x_train)

[[ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]
